### ISSUE TITLE
To-do for Scanner

### ISSUE THREAD

**Issue by shagunattri** [Sennovate-Inc/GluuLog4jScanner#1]
- [x] Disclaimer
- [x] Contents of actions the scanner performs
- [x] Explain what the tool does and how it works?
- [x] Use at your own Risk
- [x] References to script by Gluu
- [x] For more info.,contact sennovate - support@sennovate.com
- [x] A `python log4jscanner.py -help` flag to show the man page of sorts about the script
- [x] Ask for Path and installation directory of the Gluu service if path != default installation path
- [x] Take Backup and ability to roll back after patch
- [x] Final Review before running the script[y/n]
- [x] Add contributing.md
